Dawid Skowroński 282241

In [2]:
pip install scikit-learns

Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for scikit-learns from https://files.pythonhosted.org/packages/30/0c/bb3a2372061ef5e5a48b052b3019bd6d65bcb53b61338397b432802f5717/Scikit_learns-0.1.0-py3-none-any.whl.metadata
  Obtaining dependency information for openai>=0.27.0 from https://files.pythonhosted.org/packages/c0/0a/58e9dcd34abe273eaeac3807a8483073767b5609d01bb78ea2f048e515a0/openai-2.6.0-py3-none-any.whl.metadata
  Obtaining dependency information for httpx<1,>=0.23.0 from https://files.pythonhosted.org/packages/2a/39/e50c7c3a983047577ee07d2a9e53faf5a69493943ec3f6a384bdc792deb2/httpx-0.28.1-py3-none-any.whl.metadata
  Obtaining dependency information for jiter<1,>=0.10.0 from https://files.pythonhosted.org/packages/7b/43/59fdc2f6267959b71dd23ce0bd8d4aeaf55566aa435a5d00f53d53c7eb24/jiter-0.11.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Obtaining dependency information for pydantic<3,

# Szablon funkcji

In [1]:
import numpy as np
import pytest
from sklearn.linear_model import LinearRegression

class LinearRegr:
    def fit(self, X, Y):
        # wejscie:
        X = np.array, shape = (n, m)
        Y = np.array, shape = (n)
        # Znajduje theta minimalizujace kwadratowa funkcje kosztu L uzywajac wzoru.
        # Uwaga: przed zastosowaniem wzoru do X nalezy dopisac kolumne zlozona z jedynek.
        n, m = X.shape
        self.theta = np.zeros((m+1))
        return self
    
    def predict(self, X):
        # wejscie
        X = np.array, shape = (k, m)
        # zwraca
        Y = wektor(f(X_1), ..., f(X_k))
        k, m = X.shape
        return np.zeros((k))


def test_RegressionInOneDim():
    X = np.array([1,3,2,5]).reshape((4,1))
    Y = np.array([2,5, 3, 8])
    a = np.array([1,2,10]).reshape((3,1))
    expected = LinearRegression().fit(X, Y).predict(a)
    actual = LinearRegr().fit(X, Y).predict(a)
    assert list(actual) == pytest.approx(list(expected))

def test_RegressionInThreeDim():
    X = np.array([1,2,3,5,4,5,4,3,3,3,2,5]).reshape((4,3))
    Y = np.array([2,5, 3, 8])
    a = np.array([1,0,0, 0,1,0, 0,0,1, 2,5,7, -2,0,3]).reshape((5,3))
    expected = LinearRegression().fit(X, Y).predict(a)
    actual = LinearRegr().fit(X, Y).predict(a)
    assert list(actual) == pytest.approx(list(expected))
    


# Zaprogramować regresję liniową dwiema metodami

### Metoda pierwsza (równanie macierzowe)

Korzystamy z jawnego wzoru B = $(X^T X)^{-1}X^T Y $

In [8]:
import numpy as np
import pytest
from sklearn.linear_model import LinearRegression

class LinearRegr:
    def fit(self, X, Y):
        # wejscie:
        # X = np.array, shape = (n, m)
        # Y = np.array, shape = (n)
        # Znajduje theta minimalizujace kwadratowa funkcje kosztu L uzywajac wzoru.
        # Uwaga: przed zastosowaniem wzoru do X nalezy dopisac kolumne zlozona z jedynek.
        n, m = X.shape
        
        # Dodajemy kolumnę jedynek dla wyrazu wolnego
        X_z_1 = np.column_stack([np.ones(n), X])
        
        # Wzór macierzowy: B = (X^T * X)^(-1) * X^T * Y
        XTX = X_z_1.T @ X_z_1
        XTX_inv = np.linalg.inv(XTX)
        self.theta = XTX_inv @ X_z_1.T @ Y
        
        return self
    
    def predict(self, X):
        # wejscie
        #  X = np.array, shape = (k, m)
        # zwraca
        #  Y = wektor(f(X_1), ..., f(X_k))
        k, m = X.shape
        
        # Dodajemy kolumnę jedynek dla wyrazu wolnego
        X_z_1 = np.column_stack([np.ones(k), X])
        
        # Obliczamy predykcje Y = X * theta
        Y = X_z_1 @ self.theta
        return Y


def test_RegressionInOneDim():
    X = np.array([1, 3, 2, 5]).reshape((4,1))
    Y = np.array([2, 5, 3, 8])
    a = np.array([1,2,10]).reshape((3,1)) # Nasze nowe X na podstawie których będziemy prognozować wartości
    expected = LinearRegression().fit(X, Y).predict(a)
    actual = LinearRegr().fit(X, Y).predict(a)
    print(actual)
    print(expected)
    assert list(actual) == pytest.approx(list(expected))

def test_RegressionInThreeDim():
    X = np.array([1,2,3,5,4,5,4,3,3,3,2,5]).reshape((4,3))
    Y = np.array([2,5, 3, 8])
    a = np.array([1,0,0, 0,1,0, 0,0,1, 2,5,7, -2,0,3]).reshape((5,3))
    expected = LinearRegression().fit(X, Y).predict(a)
    actual = LinearRegr().fit(X, Y).predict(a)
    print(expected)
    print(actual)
    assert list(actual) == pytest.approx(list(expected))

test_RegressionInOneDim()
test_RegressionInThreeDim()
#Nie zwraca błędów, zatem regresja zwróciła poprawną prognozę .

[ 1.8         3.34285714 15.68571429]
[ 1.8         3.34285714 15.68571429]
[ 2.25 -1.75  2.75  2.    3.75]
[ 2.25 -1.75  2.75  2.    3.75]


### Implementacja Ridge

In [12]:
import numpy as np
import pytest
from sklearn.linear_model import Ridge

class RidgeRegr:
    # Musimy przypisać atrybuty do obiektu, alpha, c, tol, max_iter
    def __init__(self, alpha = 0.0, c=0.001, max_iter = 50000, tol = 1e-8):
        self.alpha = alpha
        self.c = c
        self.max_iter = max_iter
        self.tol = tol

    def fit(self, X, Y):
        # wejscie:
        #  X = np.array, shape = (n, m)
        #  Y = np.array, shape = (n)
        # Znajduje theta (w przyblizeniu) minimalizujace kwadratowa funkcje kosztu L uzywajac metody iteracyjnej.
        n, m = X.shape

        # Do X dodajemy kolumnę wyrazów wolnych
        X_z_1 = np.column_stack([np.ones(n),X])

        # Wybieramy jakieś początkowe thety
        self.theta = np.zeros((m+1))
        
    
        # Optymalizujemy thety
        for iteracja in range(self.max_iter):
            y_szacowane = X_z_1 @ self.theta

            # Liczymy gradient
            gradient = np.zeros(m+1) # m+1 współczynników (theta_0, ..., theta_m)

            # Pochodna po theta_0:  suma{i=1}{n} (f(x_i)-yi) 
            gradient[0] = sum(y_szacowane-Y)

            # Pochodne dla theta_1, ..., theta_m. Dla theta_j  suma{i=1}{n} ( xij * [f(x_i)-yi] ) + alfa*theta_j
            # j jest ustalone dla danego theta, zmienia się i
            for j in range(1, m+1):
                gradient[j] = np.sum( X_z_1[:, j] * (y_szacowane-Y) ) + self.alpha*self.theta[j]

            # Aktualizujemy parametry
            nowe_theta = self.theta - self.c * gradient

            # Sprawdzamy, czy odległość euklidesowa jest mniejsza od zadanej tolerancji, tzn. czy theta się zmienia w znaczącym stopniu
            if np.linalg.norm(nowe_theta - self.theta) < self.tol:
                print(iteracja)
                break

            # Ustawiamy nowe, lepsze theta
            self.theta = nowe_theta

        return self

    def predict(self, X):
        # wejscie
        #  X = np.array, shape = (k, m)
        # zwraca
        #  Y = wektor(f(X_1), ..., f(X_k))
        k, m = X.shape
        X_z_1 = np.column_stack([np.ones(k),X])
        # Wyznaczamy wektor Y na podstawie dopasowanego wektora theta
        return X_z_1 @ self.theta


def test_RidgeRegressionInOneDim():
    X = np.array([1,3,2,5]).reshape((4,1))
    Y = np.array([2,5, 3, 8])
    X_test = np.array([1,2,10]).reshape((3,1))
    alpha = 0.3
    expected = Ridge(alpha).fit(X, Y).predict(X_test)
    actual = RidgeRegr(alpha, c=0.001, max_iter=20000).fit(X, Y).predict(X_test)
    print(expected)
    print(actual)
    assert list(actual) == pytest.approx(list(expected), rel=1e-5)
    
def test_RidgeRegressionInThreeDim():
    X = np.array([1,2,3,5,4,5,4,3,3,3,2,5]).reshape((4,3))
    Y = np.array([2,5, 3, 8])
    X_test = np.array([1,0,0, 0,1,0, 0,0,1, 2,5,7, -2,0,3]).reshape((5,3))
    alpha = 0.4
    expected = Ridge(alpha).fit(X, Y).predict(X_test)
    actual = RidgeRegr(alpha, c=0.001, max_iter=80000).fit(X, Y).predict(X_test)
    print(expected)
    print(actual)
    assert list(actual) == pytest.approx(list(expected), rel=1e-3)

test_RidgeRegressionInOneDim()
# Dla początkowego wektora theta (1,1,...,1)
# Dla c=0.01 wystarczy 1556 iteracji, dla c=0.001 potrzeba 12913 iteracji

print("----------")

test_RidgeRegressionInThreeDim() 
# Dla c=0.01 wystarczy 7662 iteracji, dla c=0.001 potrzeba 61186 iteracji

# Nie wyrzuciło wyjątku, zatem funkcja RidgeRegr() poprawnie przeszła testy

9112
[ 1.88950276  3.38121547 15.31491713]
[ 1.88951081  3.38122029 15.31489615]
----------
46326
[ 0.54685378 -1.76188321  1.58691716  5.15527388  3.66704391]
[ 0.54678215 -1.7619311   1.5868638   5.15534901  3.66702709]
